spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sqlite
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

minio:
  url: http://localhost:4380 # minio API 포트 주소
  path: ${MINIO_PATH}
  dir:
    image: storedImage # 버킷 내 이미지 저장할 폴더명
  bucket:
    name: test  # 버킷 이름
  access:
    name: CfwrngOx2FNR73LOrckh  # access key
    secret: GMrt121O1yCb5AkZn8h2mn8byByDwKLlHAuEqdv4 # secretKey key